### ISSUE TITLE
i dont know how to use the mod cause when i load in to a game with the mod enabled via mod helper it runs round 1 as normal then just skips to the final wave

### ISSUE THREAD

**Issue by awsvincible** [mend-dev/BTD6Rogue#7]

**Comment by mend-dev** [comment]
After clicking on a map, click medium, and scroll down. The reason this happens is because I empty all of the rounds when the game starts, but I only actually what bloons are sent when you are playing the specific gamemode, and not anything else. Which is an oversight, and will be fixed in the next update
